version: "3.7"
services:
    server:
        build:
            context: ./RestAPIServer
        container_name: serverRestApi
        ports:
            - "8443:8443"
    client:
        build: 
            context: ./RestAPIClient
        container_name: clientRestApi
        depends_on: 
            server:
                condition: service_started